[runtime]
;sampler = multinest
sampler = test
verbosity = standard

[DEFAULT]
default_sample = forecast_sample
default_survey = forecast_sample
2PT_FILE = $DATA_DIR/%(default_survey)s_Roman_Deep_bin1.fits
intermediate_dir = $IA_LIB/output/temp/%(default_sample)s_fast

[pipeline]
modules =  consistency  bbn_consistency
           read_pk read_pk_lin growth
           unbiased_galaxies fast_pt fits_nz
           pk_to_cl_gg IA
           flatten_gi flatten_ii
           wgp wpp wgg
           apply_photoz_factor
           ia_like


likelihoods = iacorr
timing=T
debug=F
values = $IA_LIB/examples/values-forecast.ini
extra_output = data_vector/iacorr_chi2

fast_slow = F
first_fast_module = shear_m_bias

[polychord]
base_dir = output/y3-polychord-checkpoints
polychord_outfile_root = y3
resume = F
feedback = 3
fast_fraction = 0.1

live_points = 250
num_repeats = 30
tolerance = 0.1

[output]
filename = $IA_LIB/output/%(default_survey)s_Roman_Deep_bin1_fast.txt
format=text
privacy = F

[emcee]
walkers = 80
samples = 10000
nsteps = 5

[multinest]
max_iterations = 120000
live_points = 12000

[test]
save_dir=$IA_LIB/output/forecast_sample_Deep_bin1_fast
fatal_errors=T

[consistency]
file = $COSMOSIS_LIB/utility/consistency/consistency_interface.py

[bbn_consistency]
file = $COSMOSIS_LIB/utility/bbn_consistency/bbn_consistency.py

[read_pk]
file = $IA_LIB/direct_ia/util/read_pk/read_pk.py
pk_loc = $IA_LIB/output/pk_fid/
pk_type = matter_power_nl
distances = True

[read_pk_lin]
file = $IA_LIB/direct_ia/util/read_pk/read_pk.py
pk_loc = $IA_LIB/output/pk_fid/
pk_type = matter_power_lin
distances = False

[unbiased_galaxies]
file = $COSMOSIS_LIB/bias/no_bias/no_bias.py
use_lin_power=False

[apply_photoz_factor]
file=$IA_LIB/direct_ia/util/photoz_factor/photoz_factor.py
sample_a = %(default_sample)s_density
sample_b = %(default_sample)s_shape
do_gi=F
do_ii=F

[camb]
file = $COSMOSIS_LIB/boltzmann/camb/camb_interface.py
mode = power
lmax = 2500
feedback=3
AccuracyBoost=1.1
do_tensors = T
do_lensing = T
NonLinear = pk
halofit_version = takahashi
zmin_background = 0.
zmax_background = 4.
nz_background = 150
kmin=1e-4
kmax = 50.0
kmax_extrapolate = 500.0
nk=700

[growth]
file=$COSMOSIS_LIB/structure/growth_factor/interface.so
zmin=0.
zmax=4.
nz=401

[flatten_gi]
file = $IA_LIB/direct_ia/util/flatten_pk2/flatten_pk.py
sample_a=%(default_sample)s_density
sample_b=%(default_sample)s_shape
pk_name = galaxy_intrinsic_power
window_function=True
add_bias = False
add_intrinsic_alignments=False

[flatten_ii]
file = $IA_LIB/direct_ia/util/flatten_pk2/flatten_pk.py
sample_a=%(default_sample)s_shape
sample_b=%(default_sample)s_shape
pk_name = intrinsic_power
window_function=True
add_bias = False
add_intrinsic_alignments=False


[fits_nz]
file = $COSMOSIS_LIB/number_density/load_nz_fits/load_nz_fits.py
nz_file = %(2PT_FILE)s
data_sets = %(default_sample)s_density %(default_sample)s_shape
prefix_section = T
prefix_extension = T

[fast_pt]
file = $IA_LIB/scripts/structure/fast_pt/fast_pt_interface.py
do_ia = T
k_res_fac = 0.5
verbose = F
fastpt_folder = %(intermediate_dir)s/fastpt/

[IA]
file = $IA_LIB/scripts/tatt/tatt_interface.py
sub_lowk = F
do_galaxy_intrinsic = T
ia_model = nla


[pk_to_cl_gg]
file = $IA_LIB/scripts/nonlinear_bias/nlbias_fast.py
do_rsd = True
ell_min_linspaced = 1
ell_max_linspaced = 4
n_ell_linspaced = 5
ell_min_logspaced = 5.
ell_max_logspaced = 5.e5
n_ell_logspaced = 80
limber_ell_start = 200
ell_max_logspaced=1.e5
sig_over_dchi_exact = 3.5

lingal-lingal =
nlgal-nlgal = %(default_sample)s_density-%(default_sample)s_density
nlgal-shear = %(default_sample)s_density-%(default_sample)s_shape
nlgal-intrinsic = %(default_sample)s_density-%(default_sample)s_density

do_exact = nlgal-nlgal
do_exact = nlgal-shear
do_exact = nlgal-intrinsic
auto_only = nlgal-nlgal
auto_only = nlgal-intrinsic
pks_folder = %(intermediate_dir)s/pks/

[add_magnification]
file = $COSMOSIS_LIB/structure/magnification/add_magnification.py
include_intrinsic=T

[wgg]
file=$IA_LIB/scripts/projection/projected_corrs_legendre/legendre_interface_fast.py
sample_a = %(default_sample)s_density
sample_b = %(default_sample)s_density
correlations = wgg
include_rsd = True
include_lensing = False
include_magnification = False
include_bias=False
wgg_folder = %(intermediate_dir)s/xis/
pks_folder = %(intermediate_dir)s/pks/

[wpp]
file=$IA_LIB/direct_ia/projection/projected_corrs_limber/nicaea_interface.so
sample_a = %(default_sample)s_shape
sample_b = %(default_sample)s_shape
corr_type=1

[wgp]
file=$IA_LIB/direct_ia/projection/projected_corrs_limber/nicaea_interface.so
sample_a = %(default_sample)s_density
sample_b = %(default_sample)s_shape
corr_type=0

[ia_like]
file=$IA_LIB/direct_ia/likelihood/ialike/ialike_interface.py
apply_hartlap = F
redshifts = 1,1
ctypes = wgp wpp wgg
samples = (%(default_sample)s_density,%(default_sample)s_shape) (%(default_sample)s_shape,%(default_sample)s_shape) (%(default_sample)s_density,%(default_sample)s_density)
rmin = 6. 6. 2.
rmax = 70. 70. 70.
datafile = %(2PT_FILE)s
apply_pimax=F
